---
    - name: Display all variables/facts known for a host
      debug:
        hostvars[inventory_hostname]

    - debug:
       msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}\nserver_url: {{ zabbix_url }}
        login_user: {{ zabbix_user }}
        login_password: {{ zabbix_password }}
        host_name: {{inventory_hostname}}
        host_groups: {{ zabbix_groups }}
            ip: {{ ansible_default_ipv4.address }}"
    - name: Download Zabbix deb
      get_url:
        url: http://repo.zabbix.com/zabbix/3.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_3.0-1+xenial_all.deb
        dest: /zabbix.deb

    - name: Install Zabbix deb
      apt: deb="/zabbix.deb"
      sudo: true

    - name: Update server
      apt: update_cache=yes

    - name: Upgrade server
      apt: upgrade=dist

    - name: Installs Zabbix Agent
      apt: pkg=zabbix-agent state=installed update_cache=true

    - name: Copy Zabbix configuration files
      template: src=zabbix_agentd.conf dest=/etc/zabbix/zabbix_agentd.conf

    - name: Copy Zabbix PSK file
      template: src=zabbix_agentd.psk dest=/etc/zabbix/zabbix_agentd.psk

    - name: always restart Zabbix-agent
      service: name=zabbix-agent state=restarted
    - name: "Create a new host or update an existing host's info"
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_url }}"
        login_user: "{{ zabbix_user }}"
        login_password: "{{ zabbix_password }}"
        host_name: "{{inventory_hostname}}"
        host_groups: "{{ zabbix_groups }}"
        inventory_mode: automatic
        status: "enabled"
        state: "present"
        interfaces:
          - type: 1
            main: 1
            useip: 0
            ip: "{{ ansible_default_ipv4.address }}"
            dns: "{{inventory_hostname}}"
            port: 10050
